name: "Nix Flake Check"
on:
  push:
  pull_request:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install nix
        uses: https://github.com/cachix/install-nix-action@v31
      - name: Evaluate configurations
        run: nix shell nixpkgs#fish nixpkgs#jq --command fish ./tests/eval.fish
